on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**/*'
      - '.github/workflows/macos.yml'
      - 'tools/packaging/**/*'
      - 'assets/manpages/**/*'
      - 'tests/powershell/**/*'
      - 'build.psm1'
      - 'tools/ci.psm1'

name: 'macOS CI'
permissions:
  contents: read

defaults:
  run:
    shell: pwsh
    working-directory: powershell

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  HOMEBREW_NO_ANALYTICS: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none

jobs:
  macOSBuild:
    name: 'macOS Build'
    runs-on: macos-latest-arm64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: './powershell'

      - name: Build
        id: Build
        uses: ./.github/workflows/composite/ci-build
  macOSTest:
    name: 'macOS Test'
    runs-on: macos-latest-arm64
    needs: macOSBuild
    strategy:
      matrix:
        Purpose: ['UnelevatedPesterTests', 'ElevatedPesterTests']
        TagSet: ['CI', 'Others']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build
        id: Build
        uses: ./.github/workflows/composite/nix-test
        with:
          purpose: ${{ matrix.Purpose }}
          tagSet: ${{ matrix.TagSet }}

  packageMac:
    name: 'Package macOS'
    runs-on: macos-latest-arm64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Bootstrap Packaging
        run: |
          import-module ./build.psm1
          start-psbootstrap -package

